data_configuration:
  data_folder: "/home/ztp/workspace/dataset/aerial_imagery_dataset"
  resize:
    - 256
    - 256
model_configuration:
  channel_list:
    - 3
    - 64
    - 128
    - 256
    - 512
  output_channel: 2
  deep_supervision: False
  CGM: False
  bias: False
train_configuration:
  experiment_folder: "./models/RS_Unet3P_models"
  model_name: "Unet3P"
  experiment_result_folder: "./experiment_result/RS_Unet3P_result"
  experiment_result_file: "experiment_result.pkl"
  bg_position: 1
  num_class: 2
  batch_size: 12
  base_lr: 0.003
  epochs: 100
  epsilon: 1.0e-8
  lr_decay_ratio: 0.1
  steps:
  - 80
  - 90
  - 95
  sleep_time: 10

